import { async, ComponentFixture, TestBed, fakeAsync, tick } from '@angular/core/testing';
import { FormsModule } from '@angular/forms';
import { By }              from '@angular/platform-browser';

import { LoginComponent } from './login.component';
import { AlertsComponent } from '../alerts/alerts.component';
import { LoadingSpinnerComponent } from '../loading-spinner/loading-spinner.component';
import { Router } from '@angular/router';
import { LoginService } from '../../services/login.service';
import { UserSession } from '../../autogenerated/model/UserSession';

import { Observable } from 'rxjs';

describe('LoginComponent', () => {
  let component: LoginComponent;
  let fixture: ComponentFixture<LoginComponent>;

  let routerStub = {
    navigate: function(routes: string[]) {}
  };
  let loginServiceStub = {
    logIn: function(username: string, password: string) {}
  };
  let loginService: LoginService;
  let router: Router;

  beforeEach(async(() => {
    jasmine.MAX_PRETTY_PRINT_DEPTH = 5;
    TestBed.configureTestingModule({
      imports: [ FormsModule ],
      declarations: [ LoginComponent, AlertsComponent, LoadingSpinnerComponent ],
      providers: [
        { provide: LoginService, useValue: loginServiceStub },
        { provide: Router, useValue: routerStub }
      ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(LoginComponent);
    component = fixture.componentInstance;

    loginService = fixture.debugElement.injector.get(LoginService);
    router = fixture.debugElement.injector.get(Router);
    fixture.detectChanges();
  });


  it('should log the user in when the login form is submitted', () => {
    let spy = spyOn(loginService, 'logIn');
    component.username = 'TestUserName';
    component.password = 'TestUserPassword';
    fixture.detectChanges();

    let loginForm = fixture.debugElement.query(By.css('form'));
    loginForm.triggerEventHandler('submit', null);

    expect(loginService.logIn).toHaveBeenCalledWith('TestUserName', 'TestUserPassword');
  });

  it('should navigate to "/" when the user is correctly logged in', fakeAsync(() => {
    let spy = spyOn(loginService, 'logIn')
        .and.returnValue(Observable.of({}));
    let routerSpy = spyOn(router, 'navigate');

    component.username = 'TestUserName';
    component.password = 'TestUserPassword';
    fixture.detectChanges();

    let loginForm = fixture.debugElement.query(By.css('form'));
    loginForm.triggerEventHandler('submit', null);

    tick();

    expect(router.navigate).toHaveBeenCalledWith(['/']);
  }));

  it('should show an invalid password message when receiving 401 from the login service', fakeAsync(() => {
    let spy = spyOn(loginService, 'logIn')
        .and.returnValue(Observable.throw({ status: 401 }));

    component.username = 'TestUserName';
    component.password = 'TestWrongPassword';
    fixture.detectChanges();

    let loginForm = fixture.debugElement.query(By.css('form'));
    loginForm.triggerEventHandler('submit', null);
    tick();
    fixture.detectChanges();

    let alertMessage = fixture.debugElement.query(By.css('.alert'));
    expect(alertMessage).not.toBeNull();
    expect(alertMessage.nativeElement.textContent).toContain('Invalid user name and password combination');
  }));

  it('should show a spinner instead of the login button while logging in and show the button back when finished', fakeAsync(() => {
    let spy = spyOn(loginService, 'logIn')
        .and.returnValue(Observable.of({}).delay(0));

    component.username = 'TestUserName';
    component.password = 'TestWrongPassword';
    fixture.detectChanges();

    let loginForm = fixture.debugElement.query(By.css('form'));
    loginForm.triggerEventHandler('submit', null);
    fixture.detectChanges();

    expect(fixture.debugElement.query(By.css('button'))).toBeNull();
    expect(fixture.debugElement.query(By.css('app-loading-spinner'))).not.toBeNull();

    tick();
    fixture.detectChanges();

    expect(fixture.debugElement.query(By.css('button'))).not.toBeNull();
    expect(fixture.debugElement.query(By.css('app-loading-spinner'))).toBeNull();
  }));
});
