import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpModule } from  '@angular/http';
import { routing } from './app.routing';
import { FormsModule } from '@angular/forms';
import { ModalModule } from 'ngx-bootstrap/modal';
import { FocusModule } from 'angular2-focus';
import { NgUploaderModule } from 'ngx-uploader';

import { AppComponent } from './app.component';
import { NodesPageComponent } from './components/nodes-page/nodes-page.component';

import { ConfigApi } from './autogenerated/api/ConfigApi';
import { BASE_PATH } from './autogenerated/variables';
import { properties } from '../assets/properties';
import { NodeCreationModalComponent } from './components/node-creation-modal/node-creation-modal.component';
import { NodeComponent } from './components/node/node.component';
import { FileUploadModalComponent } from './components/file-upload-modal/file-upload-modal.component';
import { AlertsComponent } from './components/alerts/alerts.component';

@NgModule({
  declarations: [
    AppComponent, NodesPageComponent, NodeCreationModalComponent, NodeComponent, FileUploadModalComponent, AlertsComponent
  ],
  entryComponents: [NodeCreationModalComponent, FileUploadModalComponent],
  imports: [
    BrowserModule,
    routing,
    HttpModule,
    FormsModule,
    ModalModule.forRoot(),
    FocusModule.forRoot(),
    NgUploaderModule
  ],
  providers: [
    ConfigApi,
    { provide: BASE_PATH, useValue: properties.zooKeeperServiceBaseUrl }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
