import { Component, OnInit } from '@angular/core';
import { BASE_PATH } from './autogenerated/variables';
import { properties } from '../assets/properties';
import { LoginService } from './services/login.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [{ provide: BASE_PATH, useValue: properties.zooKeeperServiceBaseUrl }]
})
export class AppComponent implements OnInit {
  title = 'ZooKeeperUI';
  isLoggedIn: boolean;

  constructor(private _loginService: LoginService) {
    this.isLoggedIn = false;
  }

  ngOnInit() {
    this._loginService.loggedInObservable.subscribe(
      loggedIn => this.isLoggedIn = loggedIn,
      error => {
        console.log(error);
        // TODO
      }
    );
  }

  logOut() {
    this._loginService.logOut();
  }
}
