/**
 * ZooKeeper REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface NodeCreationRequest {
    /**
     * The name of the new node.
     */
    name: string;

    /**
     * The string data of the node.
     */
    data?: string;

}
