/**
 * ZooKeeper REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface NodeExport {
    /**
     * The name of the node (last segment of the path).
     */
    name: string;

    /**
     * The value of the node.
     */
    value?: string;

    /**
     * The value of the node.
     */
    children: Array<models.NodeExport>;

}
