import { Component, OnInit, EventEmitter } from '@angular/core';
import { ConfigApi } from '../../autogenerated/api/ConfigApi';
import { ChildrenNodes } from '../../autogenerated/model/ChildrenNodes';
import { Node } from '../../model/Node';
import { BsModalService } from 'ngx-bootstrap/modal';
import { BsModalRef } from 'ngx-bootstrap/modal/bs-modal-ref.service';
import { NodeCreationModalComponent } from '../node-creation-modal/node-creation-modal.component';
import { FileUploadModalComponent, UploadOptions } from '../file-upload-modal/file-upload-modal.component';
import { NodeExport } from '../../autogenerated/model/NodeExport';
import { AlertList, Alert, AlertType} from '../alerts/alerts.component';

@Component({
  selector: 'app-nodes-page',
  templateUrl: './nodes-page.component.html',
  styleUrls: ['./nodes-page.component.css']
})
export class NodesPageComponent implements OnInit {
  currentNode: Node;
  alerts: AlertList;
  modalRef: BsModalRef;

  constructor(private _configApi : ConfigApi,
      private modalService: BsModalService) {
    this.alerts = new AlertList();
  }

  ngOnInit() {
    this.setCurrentNode(Node.ROOT_NODE);
  }

  setCurrentNode(node: Node): void {
    this.currentNode = node;
    if (!node.hasChildren) {
      this.reloadNodeChildren(node);
    }
  }

  reloadNodeChildren(node: Node) {
    this._configApi.getNodeChildren(node.path)
      .subscribe(
        childrenNodes => {
          node.clearChildren();
          for (let childName of childrenNodes.children) {
            let childNode = node.addChildNode(childName);
            this.reloadNodeChildren(childNode);
          }
        },
        error => {
          this.onError(error);
        }
      );
  }

  openAddNodeModal() {
    this.modalRef = this.modalService.show(NodeCreationModalComponent);
    this.modalRef.content.parentNode = this.currentNode;
    (this.modalRef.content.onError as EventEmitter<string>).subscribe(errorMessage =>
      {
        this.onError(errorMessage);
      }
    );
  }

  downloadNodeReport() {
    this._configApi.getNodeExport(this.currentNode.path).subscribe(
      exportData => {
        var link = document.createElement("a");
        link.download = "zookeeper-export.json";
        link.href = "data:application/json," + JSON.stringify(exportData);
        link.click();
        this.alerts.addAlert({
          alertType: AlertType.Success,
          message: `Node exported successfully!`
        });

      }
    );
  }

  onError(error:any) {
    console.log(error);
    this.alerts.addAlert({
      alertType: AlertType.Error,
      message: `Error received from ZooKeeper REST API. Status code(${error.status}) Error message: ${error._body}`
    });
  }

  openFileUploadModal() {
    this.modalRef = this.modalService.show(FileUploadModalComponent);
    this.modalRef.content.nodePath = this.currentNode.path;
    (this.modalRef.content.onFileLoaded as EventEmitter<NodeExport>).subscribe(
      (exportOptions: UploadOptions) => {
        this._configApi.restoreNodeExport(this.currentNode.path, exportOptions.prune, exportOptions.overwriteValues, exportOptions.node)
          .subscribe(
            data => {
              this.modalRef.hide();
              this.reloadNodeChildren(this.currentNode);
              this.alerts.addAlert({
                alertType: AlertType.Success,
                message: `Nodes export successfully restored!`
              });
            },
            error => {
              this.alerts.addAlert({
                alertType: AlertType.Error,
                message: error
              });
              this.modalRef.hide();
            }
          );
      }
    );
  }
}
